backend:
  name: git-gateway
  branch: main  # أو الفرع الذي تستخدمه، مثل master

media_folder: "../static/images"  # مجلد الصور
public_folder: "/images"       # المسار العام للصور في الموقع

collections:
  - name: "products"
    label: "Products"
    folder: "../content/products"  # المجلد الذي سيحتوي على ملفات المنتجات
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
